{% set version = "3.0" %}
{% set sha256 = "e2a0601b03c9b82c0bc0b2f1e6da776ac5cf762ee9d2eb31a0e94ed303ff52fe" %}

package:
  name: mimick
  version: {{ version }}

source:
  url: https://github.com/pdimens/mimick/releases/download/{{ version }}/mimick.{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  run_exports:
    - {{ pin_subpackage('mimick', max_pin="x") }}
  script: |
    {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv
    python -c 'from juliacall import Main as jl; jl.seval("using Pkg"); jl.Pkg.develop(path="./MimickLinkedReads.jl"); jl.seval("using MimickLinkedReads")' 
  entry_points:
    - mimick = mimick.__main__:mimick
    - test_mimick = mimick.__main__:mimick_test

requirements:
  host:
    - python
    - pip
    - setuptools >=80
  run:
    - click >=8.2
    - rich-click >=1.9.3
    - python >=3.10
    - pyjuliacall >=0.9.26

test:
  commands:
    - "mimick --version"
    - "test_mimick"

about:
  home: "https://github.com/pdimens/mimick"
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: "Simulate linked-read data"
  description: |
    Mimick, formerly known as XENIA from the VISOR project, can simulate all manner of available
    linked-read chemistries (10x, haplotagging, stlfr, tellseq). It allows you to simulate an
    arbitrary number of haplotypes, set overall coverage, molecule coverage, molecules per barcode,
    whether DNA is circular, etc.
  doc_url: "https://pdimens.github.io/mimick"
  dev_url: "https://github.com/pdimens/mimick"

extra:
  recipe-maintainers:
    - pdimens
