{% set version = "" %}
{% set sha256 = "" %}

package:
  name: mimick
  version: '{{ version }}'

source:
  url: https://github.com/pdimens/mimick/releases/download/{{ version }}/mimick.{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 0
  skip: True  # [osx or py < 39]
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  run_exports:
    - {{ pin_subpackage('mimick', max_pin="x") }}
  script: ${PYTHON} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv
  entry_points:
    - mimick = src.__main__:mimick

requirements:
  host:
    - python
    - pip
    - setuptools-scm >=3.4
  run:
    - biopython
    - numpy
    - rich-click
    - pyfaidx
    - pysam
    - python
    - pywgsim

test:
  commands:
    - "mimick --version"

about:
  home: "https://github.com/pdimens/mimick"
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: "Simulate linked-read data"
  description: |
    Mimick, originally XENIA from the VISOR project, is a simple but effective way of
    simulating linked-read FASTQ data (10x, haplotagging, stlfr, tellseq). Mimick allows
    you to simulate an arbitrary number of haplotypes, set overall coverage, molecule coverage,
    and mix-match barcodes with linked-read chemistries.
  doc_url: "https://pdimens.github.io/mimick"
  dev_url: "https://github.com/pdimens/mimick"

extra:
  additional-platforms:
    - linux-aarch64
  recipe-maintainers:
    - pdimens
