name: Upload Release Tarball

on:
  push:
    tags:
    - '*' # Push events of any tag created

jobs:
  build_tarball:
    name: Upload Release Tarball
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Bump Mimick Version
        # this removes the :latest tag and replaces with versioned container
        run: |
          sed -i "s/0\.0\.0/${{ github.ref_name }}/g" mimick/__main__.py
          sed -i "s/0\.0\.0/${{ github.ref_name }}/g" pyproject.toml  
          sed -i "s/\"0.0.0\"/\"${{ github.ref_name }}\"/g" MimickLinkedReads.jl/Project.toml
      - name: Build project
        # This builds the release tarball, stripped of unneccessary things
        run: |
          mkdir artifacts
          tar --exclude="test" --exclude=".deprecated" --exclude="artifacts" --exclude="resources" --exclude=".git" --exclude="docs" --exclude=".github" -zcvf artifacts/mimick.${{ github.ref_name }}.tar.gz .
      - name: Create Release with Assets
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/mimick.${{ github.ref_name }}.tar.gz
