name: Test Mimick

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CACHE_NUMBER: 0 # increase to reset cache manually

jobs:
  Tests:
    strategy:
      matrix:
        linktype: [haplotagging, stlfr, tellseq, 10x]
    name: "Simulation Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 1

      - name: Install Mimick
        uses: prefix-dev/setup-pixi@v0.9.6
        with:
          pixi-version: v0.56.0
          cache: false
          activate-environment: true
      - run: pixi run build

      - name: Create Test Data
        run: test/create_test_data.py test

      - name: Test Single Sample ${{ matrix.linktype }}
        run: |
          mimick -t 4 --quiet -g 10 --format 10x -o single_sample/${{ matrix.linktype }} test/hap1.fa.gz test/hap2.fa.gz &&\
          zcat single_sample/${{ matrix.linktype }}.R1.fq.gz | head -8

      - name: Test Single Sample standard with masking
        run: |
          mimick -t 4 --quiet -g 10 --mask-n --format standard:stlfr -o single_sample/std_stlfr test/hap1.fa.gz test/hap2.fa.gz &&\
          zcat single_sample/std_stlfr.R1.fq.gz | head -8

      - name: Test Multisample ${{ matrix.linktype }}
        run: |
          mimick -t 4 --quiet -g 5 --format ${{ matrix.linktype }} -o ${{ matrix.linktype }}/ --vcf test/test.vcf.gz test/fasta.fa.gz &&\
          zcat ${{ matrix.linktype }}/tsk_0.R1.fq.gz | head -8

      - name: Test Multisample standard with masking
        run: |
          mimick -t 4 --quiet -g 5 --mask-n --format standard:stlfr -o std_stlfr/ --vcf test/test.vcf.gz test/fasta.fa.gz &&\
          zcat std_stlfr/tsk_0.R1.fq.gz | head -8
