name: Test Mimick

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  Tests:
    name: Test ${{ matrix.lr_from }} to ${{ matrix.lr_to }}
    strategy:
      matrix:
        lr_from: [10x, haplotagging, stlfr, tellseq]
        lr_to: [10x, haplotagging, standard, stlfr, tellseq]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          init-shell: bash
          generate-run-shell: true
          environment-file: resources/mimick.yaml
          cache-environment: true
          post-cleanup: 'all'

      - name: Install Mimick
        shell: micromamba-shell {0}
        run: |
          python3 -m pip install --upgrade build && python3 -m build
          pip install dist/*.whl

      - name: Create Test Data
        shell: micromamba-shell {0}
        run: |
          resources/create_test_data.py

      - name: Test Mimick
        shell: micromamba-shell {0}
        run: |
          mimick --lr-type ${{ matrix.lr_from }} -o ${{ matrix.lr_from }}_${{ matrix.lr_to }} -O ${{ matrix.lr_to }} --coverage 10 test.bc test.hap1.fa test.hap2.fa
          rm -r ${{ matrix.lr_from }}_${{ matrix.lr_to }}
#          mimick --lr-type haplotagging -o haptag --coverage 10 test.bc test.hap1.fa test.hap2.fa
#          mimick --lr-type haplotagging -o haptag_10x -O 10x --coverage 10 test.bc test.hap1.fa test.hap2.fa
#          mimick --lr-type haplotagging -o haptag_stlfr -O stlfr --coverage 10 test.bc test.hap1.fa test.hap2.fa
#          mimick --lr-type haplotagging -o haptag_tellseq -O tellseq --coverage 10 test.bc test.hap1.fa test.hap2.fa
#          mimick --lr-type haplotagging -o haptag_standard -O standard --coverage 10 test.bc test.hap1.fa test.hap2.fa
#
#      - name: 10x
#        shell: micromamba-shell {0}
#        run: |
#          mimick --lr-type 10x -o 10x_ --coverage 10 test.bc test.hap1.fa test.hap2.fa
#          mimick --lr-type 10x -o 10x_haptag -O haplotagging --coverage 10 test.bc test.hap1.fa test.hap2.fa
#          mimick --lr-type 10x -o 10x_stlfr -O stlfr --coverage 10 test.bc test.hap1.fa test.hap2.fa
#          mimick --lr-type 10x -o 10x_tellseq -O tellseq --coverage 10 test.bc test.hap1.fa test.hap2.fa
#          mimick --lr-type 10x -o 10x_standard -O standard --coverage 10 test.bc test.hap1.fa test.hap2.fa
#          rm -r 10x_*
#
#      - name: tellseq
#        shell: micromamba-shell {0}
#        run: |
#          mimick --lr-type tellseq -o tellseq_ --coverage 10 test.bc test.hap1.fa test.hap2.fa
#          mimick --lr-type tellseq -o tellseq_10x -O 10x --coverage 10 test.bc test.hap1.fa test.hap2.fa
#          mimick --lr-type tellseq -o tellseq_stlfr -O stlfr --coverage 10 test.bc test.hap1.fa test.hap2.fa
#          mimick --lr-type tellseq -o tellseq_haptag -O haplotagging --coverage 10 test.bc test.hap1.fa test.hap2.fa
#          mimick --lr-type tellseq -o tellseq_standard -O standard --coverage 10 test.bc test.hap1.fa test.hap2.fa
#          rm -r 10x_*
#
#      - name: stlfr
#        shell: micromamba-shell {0}
#        run: |
#          mimick --lr-type stlfr -o stlfr_ --coverage 10 test.bc test.hap1.fa test.hap2.fa
#          mimick --lr-type stlfr -o stlfr_10x -O haplotagging --coverage 10 test.bc test.hap1.fa test.hap2.fa
#          mimick --lr-type stlfr -o stlfr_tellseq -O tellseq --coverage 10 test.bc test.hap1.fa test.hap2.fa
#          mimick --lr-type stlfr -o stlfr_haptag -O haplotagging --coverage 10 test.bc test.hap1.fa test.hap2.fa
#          mimick --lr-type stlfr -o stlfr_standard -O standard --coverage 10 test.bc test.hap1.fa test.hap2.fa
