name: Test Mimick

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  Nucleotides:
    name: Test ${{ matrix.lr_from }} to ${{ matrix.lr_to }}
    strategy:
      matrix:
        lr_from: [10x, tellseq]
        lr_to: [10x, haplotagging, standard, stlfr, tellseq]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Mamba
        uses: mamba-org/setup-micromamba@v2
        with:
          init-shell: bash
          generate-run-shell: true
          environment-file: resources/mimick.yaml
          cache-environment: false
          post-cleanup: 'all'

      - name: Install Mimick
        shell: micromamba-shell {0}
        run: |
          python3 -m pip install --upgrade build && python3 -m build
          pip install dist/*.whl

      - name: Create Test Data
        shell: micromamba-shell {0}
        run: |
          resources/create_test_data.py

      - name: Test Barcode file
        shell: micromamba-shell {0}
        run: |
          mimick --lr-type ${{ matrix.lr_from }} -o ${{ matrix.lr_from }}_${{ matrix.lr_to }} -O ${{ matrix.lr_to }} --coverage 10 -q 1 nucleotides.bc test.hap1.fa test.hap2.fa &&\
          zcat ${{ matrix.lr_from }}_${{ matrix.lr_to }}.R1.fq.gz | head -8 &&\
      
      - name: Test Generated Barcodes
        shell: micromamba-shell {0}
        run: |
          mimick --lr-type ${{ matrix.lr_from }} -o ${{ matrix.lr_to }}_standard -O standard --coverage 3 -q 1 18,1000000 test.hap1.fa test.hap2.fa &&\
          zcat ${{ matrix.lr_to }}_standard.R1.fq.gz | head -8 &&\

  Combinatorial:
    name: Test ${{ matrix.lr_from }} to ${{ matrix.lr_to }}
    strategy:
      matrix:
        lr_from: [haplotagging, stlfr]
        lr_to: [10x, haplotagging, standard, stlfr, tellseq]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Mamba
        uses: mamba-org/setup-micromamba@v2
        with:
          init-shell: bash
          generate-run-shell: true
          environment-file: resources/mimick.yaml
          cache-environment: false
          post-cleanup: 'all'

      - name: Install Mimick
        shell: micromamba-shell {0}
        run: |
          python3 -m pip install --upgrade build && python3 -m build
          pip install dist/*.whl

      - name: Create Test Data
        shell: micromamba-shell {0}
        run: |
          resources/create_test_data.py

      - name: Test Barcode file
        shell: micromamba-shell {0}
        run: |
          mimick --lr-type ${{ matrix.lr_from }} -o ${{ matrix.lr_from }}_${{ matrix.lr_to }} -O ${{ matrix.lr_to }} --coverage 10 -q 1 combinatorial.bc test.hap1.fa test.hap2.fa &&\
          zcat ${{ matrix.lr_from }}_${{ matrix.lr_to }}.R1.fq.gz | head -8 &&\
      
      - name: Test Generated Barcodes
        shell: micromamba-shell {0}
        run: |
          mimick --lr-type ${{ matrix.lr_from }} -o ${{ matrix.lr_from }}_standard -O standard --coverage 3 -q 1 8,200 test.hap1.fa test.hap2.fa &&\
          zcat ${{ matrix.lr_from }}_standard.R1.fq.gz | head -8 &&\
