name: Test Mimick

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  Nucleotides:
    name: "Test ${{ matrix.lr_to }}"
    strategy:
      matrix:
        format: [10x, haplotagging, standard, stlfr, tellseq]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Mamba
        uses: mamba-org/setup-micromamba@v2
        with:
          init-shell: bash
          generate-run-shell: true
          environment-file: resources/mimick.yaml
          cache-environment: false
          post-cleanup: 'all'

      - name: Install Mimick
        shell: micromamba-shell {0}
        run: |
          python3 -m pip install --upgrade build && python3 -m build
          pip install dist/*.whl
          python -c 'from juliacall import Main as jl; jl.seval("using Pkg"); jl.Pkg.develop(path="./MimickLinkedReads.jl"); jl.seval("using MimickLinkedReads")' 

      - name: Create Test Data
        shell: micromamba-shell {0}
        run: |
          cd test/ && ./create_test_data.py

      - name: Test Single Sample
        shell: micromamba-shell {0}
        run: |
          mimick -t 4 -g 10 --format ${{ matrix.format}} -o single_sample/${{ matrix.format}} test/hap1.fa test/hap2.fa &&\
          zcat single_sample/${{ matrix.format}}.R1.fq.gz | head -8
      
      - name: Test Multisample
        shell: micromamba-shell {0}
        run: |
          mimick -t 4 -g 5 --format ${{ matrix.format}} -o ${{ matrix.format}}/ --vcf test/test.vcf test/fasta.fa &&\
          zcat ${{ matrix.format }}/tsk_0.R1.fq.gz | head -8
