name: Test Mimick

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CACHE_NUMBER: 0 # increase to reset cache manually

jobs:
  Tests:
    strategy:
      matrix:
        linktype: [haplotagging, stlfr, tellseq, 10x, standard:stlfr]
    name: "Simulation Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0
        with:
          fetch-depth: 1

      - name: Install Mimick
        uses: prefix-dev/setup-pixi@v0.9.6
        with:
          pixi-version: v0.56.0
          cache: false
          activate-environment: true
      - run: pixi run build

      - name: Create Test Data
        run: test/create_test_data.py test

      - name: Set safe linktype (replace colons for file paths)
        id: safe
        run: echo "linktype=${{ matrix.linktype }}" | sed 's/:/-/g' >> "$GITHUB_OUTPUT"

      - name: Test Single Sample ${{ matrix.linktype }}
        run: |
          mimick -t 4 --quiet -g 10 --format ${{ matrix.linktype }} \
            -o single_sample/${{ steps.safe.outputs.linktype }} test/hap1.fa.gz test/hap2.fa.gz &&\
          zcat single_sample/${{ steps.safe.outputs.linktype }}.R1.fq.gz | head -8

      - name: Test Single Sample ${{ matrix.linktype }} with masking
        run: |
          mimick -t 4 --quiet -g 10 --mask-n --format ${{ matrix.linktype }} \
            -o single_sample_mask/${{ steps.safe.outputs.linktype }} test/hap1.fa.gz test/hap2.fa.gz &&\
          zcat single_sample_mask/${{ steps.safe.outputs.linktype }}.R1.fq.gz | head -8

      - name: Test Multisample ${{ matrix.linktype }}
        run: |
          mimick -t 4 --quiet -g 5 --format ${{ matrix.linktype }} \
            -o ${{ steps.safe.outputs.linktype }}/ --vcf test/test.vcf.gz test/fasta.fa.gz &&\
          zcat ${{ steps.safe.outputs.linktype }}/tsk_0.R1.fq.gz | head -8

      - name: Test Multisample ${{ matrix.linktype }} with masking
        run: |
          mimick -t 4 --quiet -g 5 --mask-n --format ${{ matrix.linktype }} \
            -o ${{ steps.safe.outputs.linktype }}_mask/ --vcf test/test.vcf.gz test/fasta.fa.gz &&\
          zcat ${{ steps.safe.outputs.linktype }}_mask/tsk_0.R1.fq.gz | head -8